// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1607029135);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1607029255);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1607028895);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1607029015);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1607029375);
user_pref("browser.cache.disk.amount_written", 430);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KE");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 23 Nov 2020 15:46:42 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1607029137);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"dcb7a46e-fc95-4d2f-80bd-f7adfcd579f7\",\"default-theme@mozilla.org\":\"82f9d5d9-9bd9-402b-86a0-1f874831e2f9\",\"google@search.mozilla.org\":\"73484cff-6386-4219-a0f9-4da7de5a4d56\",\"amazondotcom@search.mozilla.org\":\"68c47c43-28c3-4bff-862b-4f22f2387c11\",\"bing@search.mozilla.org\":\"85576ce6-cc52-475b-b9cf-7cba17d6c770\",\"ddg@search.mozilla.org\":\"05c47e38-7b6a-4e8e-87e7-6715edfdc260\",\"twitter@search.mozilla.org\":\"ca652f9b-07b4-4b60-a2f6-d69e9931c277\",\"wikipedia@search.mozilla.org\":\"36ca4bfb-c186-47c0-b7c4-3ee80a9d731b\"}");
user_pref("idle.lastDailyNotification", 1606904343);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.root.imap", "/home/moringaaccess/.thunderbird/qr11fiv4.default-release/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "ed2ea00d-dcde-462f-8003-b46380f29ea");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1606904343);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "a14692b9-4af9-44f5-9687-f0372740c5c5");
user_pref("services.blocklist.pinning.checked", 1607029015);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1607025500081\"");
user_pref("services.settings.last_update_seconds", 1607029015);
user_pref("services.settings.main.hijack-blocklists.last_check", 1607029015);
user_pref("services.settings.main.language-dictionaries.last_check", 1607029015);
user_pref("services.settings.main.sites-classification.last_check", 1607029015);
user_pref("services.settings.security.onecrl.checked", 1607029015);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1606904343);
user_pref("toolkit.telemetry.cachedClientID", "8c4b9ea4-2c00-4cc8-8c32-d345d732950b");
user_pref("toolkit.telemetry.prompted", 2);
